### ISSUE TITLE
ip triggering multiple scenarios with different type (ban, captcha, customtype) only see last alert type in blocklist map

### ISSUE THREAD

**Issue by aderumier** [crowdsecurity/cs-haproxy-bouncer#11]
Hi,

Today, I had an attack from an ip triggering multiple scenarios.

Currently, I have some custom profiles, for some scenario (mainly http scan) , to use use "ban" type, but a custom "logononly" type

```
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip" && Alert.GetScenario() in ["crowdsecurity/http-crawl-non_statics", "crowdsecurity/http-probing"]
decisions:
 - type: logonly
   duration: 4h
```
Like it, I'm able to manually analyse this attack (as I can have false positive), and manually block the ip.

The problem, is that the blacklist sync only see last alert type.

So, the ip was triggering logonly,ban,longonly,ban,.....

```
#  echo "show map /var/lib/crowdsec/lua/haproxy/community_blocklist.map" | socat unix-connect:/var/run/haproxy.socket stdio |grep 103.123.169.94
0x7f9830cb1570 103.123.169.94 ban
~#  echo "show map /var/lib/crowdsec/lua/haproxy/community_blocklist.map" | socat unix-connect:/var/run/haproxy.socket stdio |grep 103.123.169.94
0x7f9830cb1570 103.123.169.94 ban
#  echo "show map /var/lib/crowdsec/lua/haproxy/community_blocklist.map" | socat unix-connect:/var/run/haproxy.socket stdio |grep 103.123.169.94
0x7f9830cb1570 103.123.169.94 logonly
#  echo "show map /var/lib/crowdsec/lua/haproxy/community_blocklist.map" | socat unix-connect:/var/run/haproxy.socket stdio |grep 103.123.169.94
0x7f9830cb1570 103.123.169.94 logonly
#  echo "show map /var/lib/crowdsec/lua/haproxy/community_blocklist.map" | socat unix-connect:/var/run/haproxy.socket stdio |grep 103.123.169.94
0x7f9830cb1570 103.123.169.94 ban

```

and it's wasn't correctly blocked.

Is is possible to sync only some specific "type" in the haproxy map ?  
Or Configure some kind of type priority ?  (I an ip is already ban, it shouldn't be overrided with captcha for example)
